const fs = require('fs');

const dePath = 'c:\\Users\\myspa\\Documents\\Ecom bois\\src\\locales\\de\\temp_dash2.json';
const frPath = 'c:\\Users\\myspa\\Documents\\Ecom bois\\src\\locales\\fr\\temp_dash2.json';

const deNew = {
  "profile": {
    "toast_data_saved": "Ihre Daten wurden erfolgreich gespeichert!",
    "toast_data_error": "Fehler beim Speichern des Profils.",
    "toast_settings_saved": "Einstellungen gespeichert!",
    "toast_settings_error": "Fehler beim Aktualisieren der Einstellungen",
    "toast_password_fields_empty": "Bitte füllen Sie alle Passwortfelder aus.",
    "toast_password_too_short": "Das neue Passwort muss mindestens 6 Zeichen lang sein.",
    "toast_password_mismatch": "Die Passwörter stimmen nicht überein.",
    "toast_password_success": "Passwort erfolgreich geändert!",
    "toast_password_wrong": "Altes Passwort falsch oder Fehler aufgetreten.",
    "toast_logout_success": "Sie wurden abgemeldet.",
    "toast_logout_error": "Fehler beim Abmelden.",
    "title": "Mein Kundenprofil",
    "verified_account": "Verifiziertes Kundenkonto",
    "tab_contact": "Kontakt & Lieferung",
    "tab_security": "Sicherheit & Einstellungen",
    "contact_billing_info": "Kontakt- & Rechnungsinformationen",
    "edit_btn": "Bearbeiten",
    "first_last_name": "Vor- & Nachname",
    "not_specified": "Nicht angegeben",
    "delivery_phone": "Liefertelefon",
    "phone_sub": "Wird vom Spediteur für das Zeitfenster verwendet",
    "delivery_address": "Lieferadresse",
    "no_address": "Keine Adresse hinterlegt",
    "forklift_access": "Zugang für Mitnahmestapler",
    "forklift_delivery": "Lieferung mit Mitnahmestapler:",
    "forklift_desc": "Unsere Holzpaletten werden so nah wie möglich an Ihrem Lagerort (Schuppen, Garage, Hof) abgestellt, vorausgesetzt, es ist genügend Platz vorhanden (Mindestdurchfahrtsbreite 2,20m).",
    "full_name_company": "Vollständiger Name / Firma",
    "placeholder_name": "Z.B.: Max Mustermann",
    "phone_number": "Telefonnummer",
    "placeholder_phone": "Z.B.: 0151 12345678",
    "address_street": "Adresse (Hausnummer und Straße)",
    "placeholder_address": "Z.B.: Eichenstraße 15",
    "postal_code": "Postleitzahl",
    "placeholder_postal": "Z.B.: 10115",
    "city": "Stadt",
    "placeholder_city": "Z.B.: Berlin",
    "country": "Land",
    "country_france": "Frankreich",
    "country_belgium": "Belgien",
    "country_luxembourg": "Luxemburg",
    "country_switzerland": "Schweiz",
    "country_germany": "Deutschland",
    "access_details": "Zugangsdetails für den Mitnahmestapler (optional)",
    "placeholder_access": "Z.B.: Schotterweg, 3m Tor, Lagerung vor der Garage links...",
    "cancel": "Abbrechen",
    "saving": "Speichern...",
    "save_data": "Meine Daten speichern",
    "communication_settings": "Kommunikationseinstellungen",
    "order_delivery_notifs": "Bestell- & Lieferbenachrichtigungen",
    "order_delivery_desc": "Erhalten Sie per E-Mail Zahlungsbestätigungen und Lieferbenachrichtigungen des LKWs.",
    "promos_tips": "Sonderangebote & Heiztipps",
    "promos_tips_desc": "Seien Sie über Preise in der Nebensaison und Tipps zur Holzlagerung informiert.",
    "account_security": "Kontosicherheit & Passwort",
    "current_password": "Aktuelles Passwort",
    "placeholder_current_password": "Ihr aktuelles Passwort",
    "show_hide": "Anzeigen/verbergen",
    "new_password": "Neues Passwort",
    "placeholder_new_password": "Mindestens 6 Zeichen",
    "confirm_new_password": "Neues Passwort bestätigen",
    "placeholder_confirm_new_password": "Neues Passwort erneut eingeben",
    "updating": "Wird aktualisiert...",
    "update_password": "Passwort aktualisieren",
    "active_session": "Aktive Sitzung auf diesem Gerät",
    "logout": "Von Brennholzkaufen abmelden"
  }
};

const frNew = {
  "profile": {
    "toast_data_saved": "Vos données ont été enregistrées avec succès !",
    "toast_data_error": "Erreur lors de l'enregistrement du profil.",
    "toast_settings_saved": "Paramètres enregistrés !",
    "toast_settings_error": "Erreur lors de la mise à jour des paramètres",
    "toast_password_fields_empty": "Veuillez remplir tous les champs de mot de passe.",
    "toast_password_too_short": "Le nouveau mot de passe doit comporter au moins 6 caractères.",
    "toast_password_mismatch": "Les mots de passe ne correspondent pas.",
    "toast_password_success": "Mot de passe modifié avec succès !",
    "toast_password_wrong": "Ancien mot de passe incorrect ou erreur survenue.",
    "toast_logout_success": "Vous avez été déconnecté.",
    "toast_logout_error": "Erreur lors de la déconnexion.",
    "title": "Mon profil client",
    "verified_account": "Compte client vérifié",
    "tab_contact": "Contact & Livraison",
    "tab_security": "Sécurité & Paramètres",
    "contact_billing_info": "Informations de contact et de facturation",
    "edit_btn": "Modifier",
    "first_last_name": "Prénom & Nom",
    "not_specified": "Non spécifié",
    "delivery_phone": "Téléphone de livraison",
    "phone_sub": "Utilisé par le transporteur pour le créneau horaire",
    "delivery_address": "Adresse de livraison",
    "no_address": "Aucune adresse renseignée",
    "forklift_access": "Accès pour chariot embarqué",
    "forklift_delivery": "Livraison avec chariot embarqué :",
    "forklift_desc": "Nos palettes de bois sont déposées au plus près de votre lieu de stockage (hangar, garage, cour), à condition que l'espace soit suffisant (largeur de passage minimale de 2,20m).",
    "full_name_company": "Nom complet / Entreprise",
    "placeholder_name": "Ex. : Jean Dupont",
    "phone_number": "Numéro de téléphone",
    "placeholder_phone": "Ex. : 06 12 34 56 78",
    "address_street": "Adresse (Numéro et Rue)",
    "placeholder_address": "Ex. : 15 rue des Chênes",
    "postal_code": "Code postal",
    "placeholder_postal": "Ex. : 75001",
    "city": "Ville",
    "placeholder_city": "Ex. : Paris",
    "country": "Pays",
    "country_france": "France",
    "country_belgium": "Belgique",
    "country_luxembourg": "Luxembourg",
    "country_switzerland": "Suisse",
    "country_germany": "Allemagne",
    "access_details": "Détails d'accès pour le chariot embarqué (optionnel)",
    "placeholder_access": "Ex. : Chemin en gravier, portail de 3m, stockage devant le garage à gauche...",
    "cancel": "Annuler",
    "saving": "Enregistrement...",
    "save_data": "Enregistrer mes données",
    "communication_settings": "Paramètres de communication",
    "order_delivery_notifs": "Notifications de commande & de livraison",
    "order_delivery_desc": "Recevez par e-mail les confirmations de paiement et les notifications de livraison du camion.",
    "promos_tips": "Offres spéciales & Conseils de chauffage",
    "promos_tips_desc": "Soyez informé des prix basse saison et des conseils de stockage du bois.",
    "account_security": "Sécurité du compte & Mot de passe",
    "current_password": "Mot de passe actuel",
    "placeholder_current_password": "Votre mot de passe actuel",
    "show_hide": "Afficher/masquer",
    "new_password": "Nouveau mot de passe",
    "placeholder_new_password": "Au moins 6 caractères",
    "confirm_new_password": "Confirmer le nouveau mot de passe",
    "placeholder_confirm_new_password": "Saisir à nouveau le nouveau mot de passe",
    "updating": "Mise à jour...",
    "update_password": "Mettre à jour le mot de passe",
    "active_session": "Session active sur cet appareil",
    "logout": "Se déconnecter de Brennholzkaufen"
  }
};

function update(path, newData) {
  const content = JSON.parse(fs.readFileSync(path, 'utf8'));
  Object.assign(content, newData);
  fs.writeFileSync(path, JSON.stringify(content, null, 2));
}

update(dePath, deNew);
update(frPath, frNew);

console.log('JSON files updated');
